name: 'Manual Workflow Trigger'
description: 'Manually trigger a workflow'
inputs:
  github-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
  label:
    description: 'The label that needs to be applied to run the workflow'
    required: true
outputs:
  run:
    description: '"true" if job should run, "false" otherwise'
runs:
  using: 'node12'
  main: 'dist/index.js'
