name: concurrent
on:
  workflow_dispatch:
    inputs:
      core-api:
        type: boolean
        description: ore-api

      bio-pusher:
        type: boolean
        description: bio-pusher-services

jobs:
  check:
    name: Check if job should run
    runs-on: ubuntu-20.04
    steps:
      - name: see
        uses: actions/github-script@v6
        with:
          script: |
            const projects = fromJSON(github.event.inputs)
            console.log(projects)
