name: concurrent
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - develop
    types: [labeled]
  issue_comment:
    types: [created, edited]

jobs:
  check:
    name: Check if job should run
    runs-on: ubuntu-20.04
    steps:
      - name: see
        run: |
          sleep 100000
