name: concurrent
on:
  workflow_dispatch:
    inputs:
      core-api:
        type: boolean
        description: ore-api

      bio-pusher:
        type: boolean
        description: bio-pusher-services

jobs:
  check:
    name: Check if job should run
    runs-on: ubuntu-20.04
    outputs:
      selectedProjects: ${{env.selectedProjects}}
    steps:
      - name: see
        uses: actions/github-script@v6
        with:
          script: |
            const inputs = context.payload.inputs
            const projects = Object.entries(inputs).filter(input=>input[1]==='true').map(input=>input[0]).join()
            if(projects===''){
              throw new Error('No project selected')
            }
            core.exportVariable('selectedProjects', projects);
      - run: echo ${{env.selectedProjects}}
  build-bio-web-app:
    needs: [check]
    if: success()
    uses: ./.github/workflows/test-workflow-call.yml
    with:
      projects: ${{needs.check.outputs.selectedProjects}}
