name: concurrent
on:
  workflow_dispatch:
    inputs:
      core-api:
        type: boolean
        description: ore-api

      bio-pusher:
        type: boolean
        description: bio-pusher-services

jobs:
  check:
    name: Check if job should run
    runs-on: ubuntu-20.04
    steps:
      - name: see
        run: |
          echo ${{toJSON(github.event.inputs)}} ${{github.event.inputs.bio-pusher}}
