name: concurrent
on:
  workflow_dispatch:
    inputs:
      core-api:
        type: boolean
        description: ore-api
        required: true
      bio-pusher:
        type: boolean
        description: bio-pusher-services
        required: true
jobs:
  check:
    name: Check if job should run
    runs-on: ubuntu-20.04
    steps:
      - name: see
        run: |
          echo ${{github.event.inputs.core-api}} ${{github.event.inputs.bio-pusher}}
