name: concurrent
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - develop
    types: [labeled]
  issue_comment:
    types: [created, edited]

concurrency:
  group: test-${{ github.head_ref || github.event.issue.pull_request.url }}
  cancel-in-progress: true
jobs:
  check:
    name: Check if job should run
    runs-on: ubuntu-20.04
    steps:
      - name: see
        run: |
          echo ${{ github.head_ref }}
          echo ${{ github.event.issue.pull_request }}
          sleep 100000
