name: Deploy
on:
  push:
    branches: [release]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-20.04
    needs: [check]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: release
          fetch-depth: 0
      - name: deploy actual
        run: |
          echo ${{github.sha}}

          git push -f https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/carmen-staging.git release:master
