name: End-to-end tests
on:
  workflow_dispatch:
  deployment_status:

jobs:
  cypress-run-e2e:
    if: (github.event.deployment_status.state == 'success' && github.event.deployment.environment == 'carmen-staging') || github.event_name == 'workflow_dispatch'
    runs-on: windows-latest

    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run 3 copies of the current job in parallel
        containers: [1, 2]
    outputs:
      pr_sha: ${{ steps.pr_sha.outputs.pr_sha }}
    steps:
      # if trigger on pr
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        continue-on-error: true
        with:
          node-version: 14.18.1

      - name: Cypress run - Cypress Dashboard
        run: |
          npm install
