name: Main
on:
  workflow_dispatch:
    branches:
      - "develop"
      - "hotfix/*"
  push:

jobs:
  test:
    name: run test
    runs-on: ubuntu-20.04
    steps:
      - run: echo "yeah"
  check:
    name: Check if job should run
    runs-on: ubuntu-20.04
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      # - run: git fetch --prune --unshallow
      # - name: Dump GitHub context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJSON(github) }}
      #   run: echo "$GITHUB_CONTEXT"

      - name: Commit report
        id: get-tag
        run: |
          git config --global user.name 'release'
          git config --global user.email 'release.manager@biorender.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git fetch --prune --tags
          t=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "::set-output name=latest_tag::$t"

      - name: Create tag
        uses: actions/github-script@v5
        id: set-release
        with:
          # script: |
          #   github.rest.git.createRef({
          #     owner: context.repo.owner,
          #     repo: context.repo.repo,
          #     ref: `refs/tags/${{steps.generate_tag.outputs.new_tag}}`,
          #     sha: context.sha
          #   })
          script: |
            const script = require('./release.js')

            await script({github, context, core, tag: `${{steps.latest-tag.outputs.latest_tag}}` })

          result-encoding: string
      - name: get
        if: success()
        run: echo ${{steps.set-release.outcome}}
  call-a:
    needs: [check]
    if: success()
    uses: ./.github/workflows/workflow-a.yml
    secrets:
      SENTRY_AUTH_TOKEN_CLIENT: ${{secrets.SENTRY_AUTH_TOKEN_CLIENT}}
      AWS_ACCESS_KEY_ID_FOR_AWS_DEV_ACCOUNT: ${{secrets.AWS_ACCESS_KEY_ID_FOR_AWS_DEV_ACCOUNT}}
  slack-fail:
    if: failure()
    needs: [check]
    name: run test
    runs-on: ubuntu-20.04
    steps:
      - name: send failed slack
        if: needs.check.result != 'success'
        run: |
          echo "Fail"
