name: Main
on:
  workflow_dispatch:
  push:

jobs:
  check:
    name: Check if job should run
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      # - run: git fetch --prune --unshallow
      # - name: Dump GitHub context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJSON(github) }}
      #   run: echo "$GITHUB_CONTEXT"
      - name: run script
        id: generate_tag
        run: |
          echo "Fetch tags"
          git fetch --prune --tags
          t=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo $t
          TODAY=`date +%y-%m-%d`
          echo $TODAY
          version="01"
          new_tag="prod-$TODAY-$version"
          echo $new_tag
          echo "::set-output name=new_tag::$new_tag"
      # - name: tag name
      #   run: |
      #     echo "${{steps.generate_tag.outputs.new_tag}}"
      - name: Commit report
        run: |
          git config --global user.name 'someint'
          git config --global user.email 'something@carmen.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
      - name: Create tag
        uses: actions/github-script@v5
        with:
          # script: |
          #   github.rest.git.createRef({
          #     owner: context.repo.owner,
          #     repo: context.repo.repo,
          #     ref: `refs/tags/${{steps.generate_tag.outputs.new_tag}}`,
          #     sha: context.sha
          #   })
          script: |
            const script = require('./release.js')
            await script({github, context, core }}})
