name: Main
on:
  workflow_dispatch:

jobs:
  check:
    name: Check if job should run
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "ready to tag and deploy"
          t=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo $t
      # - name: Create tag
      #   uses: actions/github-script@v5
      #   with:
      #     script: |
      #       github.rest.git.createRef({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         ref: 'refs/tags/test-tag',
      #         sha: context.sha
      #       })
