name: Main
on:
  workflow_dispatch:
    branches:
      - "develop"
      - "hotfix/*"
  push:

jobs:
  test:
    name: run test
    runs-on: ubuntu-20.04
    steps:
      - run: exit 1
  check:
    name: Check if job should run
    runs-on: ubuntu-20.04
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      # - run: git fetch --prune --unshallow
      # - name: Dump GitHub context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJSON(github) }}
      #   run: echo "$GITHUB_CONTEXT"

      - name: Commit report
        id: get-tag
        run: |
          git config --global user.name 'someint'
          git config --global user.email 'something@carmen.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git fetch --prune --tags
          t=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "::set-output name=latest_tag::$t"

      - name: Create tag
        uses: actions/github-script@v5
        id: set-release
        with:
          # script: |
          #   github.rest.git.createRef({
          #     owner: context.repo.owner,
          #     repo: context.repo.repo,
          #     ref: `refs/tags/${{steps.generate_tag.outputs.new_tag}}`,
          #     sha: context.sha
          #   })
          script: |
            const script = require('./release.js')

            await script({github, context, core, tag: `${{steps.latest-tag.outputs.latest_tag}}` })
            console.log(returned)
          result-encoding: string
      - name: get
        if: always()
        run: echo ${{steps.run_script.outcome}}
  slack-fail:
    if: always()
    needs: [check]
    name: run test
    runs-on: ubuntu-20.04
    steps:
      - name: send failed slack
        if: needs.check.result != 'success'
        run: |
          echo "Fail"
