name: Main
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - develop
    types: [labeled]

jobs:
  find-out:
    runs-on: windows-latest
    steps:
      - name: "step-checkout"
        uses: actions/checkout@v1
      - name: "step-log"
        run: |
          echo "[B] github.ref: ${{github.event.pull_request.head.ref}} ${{github.base_ref}}"
  jest-run:
    if: github.event.pull_request.head.ref == 'develop' || github.event.label.name == 'Run Tests'
    runs-on: windows-latest
    steps:
      - name: "step-log"
        run: |
          echo "[B] github.ref: ${{github.event.pull_request.head.ref}} ${{github.base_ref}}"
    # strategy:
    #   # when one test fails, DO NOT cancel the other
    #   # containers, because this will kill Cypress processes
    #   # leaving the Dashboard hanging ...
    #   # https://github.com/cypress-io/github-action/issues/48
    #   fail-fast: false
    #   matrix:
    #     # run 3 copies of the current job in parallel
    #     containers: [1, 2, 3]
    # steps:
    #   - name: Checkout
    #     uses: actions/checkout@v1
    #   - name: Cypress run
    #     uses: cypress-io/github-action@v2
    #     with:
    #       record: true
    #       parallel: true
    #       group: "Actions example"
    #       start: "npm run test:ci:record"
    #       wait-on: "http://localhost:8888"
    #     env:
    #       # pass the Dashboard record key as an environment variable
    #       CYPRESS_RECORD_KEY: "be2efe05-65a6-477e-ba04-9ed19fd53a83"
    #       # Recommended: pass the GitHub token lets this action correctly
    #       # determine the unique run id necessary to re-run the checks
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  jest-pass:
    if: ${{ always() }}
    runs-on: windows-latest
    needs: jest-run
    steps:
      - name: echo
        run: echo "${{needs.jest-run.result}} ${{needs.jest-run.result != 'success' || needs.jest-run.result != 'skipped' }}"
      - name: Check all cypress test matrix status
        if: ${{ needs.jest-run.result != 'success' && needs.jest-run.result != 'skipped' }}
        run: exit 1
    # - name: Run E2E tests
    #   uses: cypress-io/github-action@v2
    #   with:
    #     start: "npm run test:ci:record"
    #     wait-on: "http://localhost:8888"
    #     # let's see if the Test Runner handles url in the config
    #     # https://github.com/cypress-io/cypress/issues/5466
    #     config: baseUrl=http://localhost:8888
