name: Main
on:
  workflow_dispatch:
    branches:
      - "develop"
      - "hotfix/*"
  push:

jobs:
  check:
    name: Check if job should run
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      # - run: git fetch --prune --unshallow
      # - name: Dump GitHub context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJSON(github) }}
      #   run: echo "$GITHUB_CONTEXT"

      - name: Commit report
        run: |
          git config --global user.name 'someint'
          git config --global user.email 'something@carmen.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Create tag
        uses: actions/github-script@v5
        id: set-release
        with:
          # script: |
          #   github.rest.git.createRef({
          #     owner: context.repo.owner,
          #     repo: context.repo.repo,
          #     ref: `refs/tags/${{steps.generate_tag.outputs.new_tag}}`,
          #     sha: context.sha
          #   })
          script: |
            const script = require('./release.js')
            git fetch --prune --tags
            const teg = git describe --tags `git rev-list --tags --max-count=1`      
            console.log.log(teg)
            await script({github, context, core })
            console.log(returned)
          result-encoding: string

      - name: print name
        run: |
          echo ${{ env.author }}
