name: Bio-web-app deployment

on:
  workflow_call:
  push:
    branches:
      - main

jobs:
  deploy-staging:
    name: Build and push bio-web-app to s3 (Staging)
    runs-on: ubuntu-latest
    steps:
      - name: Deploy bio web app
        run: |
          echo "Deployed bio web app"
