name: Bio-web-app deployment

on:
  workflow_run:
    workflows: [Main]
    types: [completed]
  push:
    branches:
      - master

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name != 'workflow_run' }}
    steps:
      - run: echo 'Should deploy to staging'

  deploy-staging:
    name: Build and push bio-web-app to s3 (Staging)
    runs-on: ubuntu-latest
    needs: on-success
    steps:
      - name: Deploy bio web app
        run: |
          echo "Deployed bio web app"
