name: Release Notes

on:
  repository_dispatch:
    types: [release-notes]
  workflow_call:
    inputs:
      project:
        required: true
        type: string

jobs:
  release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Version
        shell: bash
        run: npx nx version ${{ github.event.client_payload.project || inputs.project }}
