name: Build bio-web-app (staging, production)

on:
  workflow_dispatch:

  workflow_call:
    inputs:
      projects:
        required: true
        type: string
      environment:
        required: true
        type: string
jobs:
  build-staging:
    name: Build and push bio-web-app to s3 (Staging)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create deployment
        uses: actions/github-script@v6
        with:
          script: |
            const deployment = await github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: '${{github.sha}}',
              required_contexts: ['Unit tests'],
              environment: 'biorender-staging-core-api',
              description: "aws",
              auto_merge: false,
              payload: {
                deployment_agent: 'aws'
              }
            })
