name: Build bio-web-app (staging, production)

on:
  push:
    branches: [release]
  workflow_call:
    inputs:
      projects:
        required: true
        type: string
      environment:
        required: true
        type: string
jobs:
  build-staging:
    name: Build and push bio-web-app to s3 (Staging)
    runs-on: ubuntu-latest
    steps:
      - name: create deployment
        uses: actions/github-script@v6
        with:
          script: |
            const projects =`${{inputs.projects}}`.split(',')
            const targetDeployments = []
            for await (const project of projects){
              const existedDeployments = await github.rest.repos.listDeployments({
                owner: context.repo.owner,
                repo: context.repo.repo,
                sha: `${{github.sha}}`,
              });
              const existedDeploymentOfProject = existedDeployments.data.filter(
                (deployment) =>
                  deployment.environment.includes("biorender-staging") &&
                  (deployment.payload.project == project)
              );
              console.log(existedDeploymentOfProject)
              if (existedDeploymentOfProject.length == 0){
                const deployment = await github.rest.repos.createDeployment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: '${{github.sha}}',
                  required_contexts: [],
                  environment: `${{inputs.environment}}-${project}`,
                  description: "aws",
                  auto_merge: false,
                  payload: {
                    deployment_agent: 'aws',
                    project,
                  }
                })
              }     
            }
