name: actors
on:
  workflow_dispatch:
    branches:
      - "develop"
  schedule:
    - cron: "* * * * *"

jobs:
  test:
    name: run test
    runs-on: ubuntu-20.04
    steps:
      - name: set name
        id: set-name
        run: |
          echo "${{ github.actor }}"
