name: actors
on:
  workflow_dispatch:
    branches:
      - "develop"
  schedule:
    - cron: "* * * * *"

jobs:
  test:
    name: run test
    runs-on: ubuntu-20.04
    steps:
      - name: set name
        id: set-name
        run: |
          if ${{ github.actor }}
          then
            echo "::set-output name=actor::${{github.actor}}"
          fi

      - name: echo
        run: |
          echo "${{steps.set-name.outputs.actor }}"
