name: actors
on:
  workflow_dispatch:
    branches:
      - "develop"
  schedule:
    - cron: "* * * * *"

jobs:
  test:
    name: run test
    runs-on: ubuntu-20.04
    steps:
      - run: |
        echo "${{ github.actor }}""
        echo "$GITHUB_ACTOR"
        
 
