name: Reusable workflow example

on:
  workflow_call:
    secrets:
      SENTRY_AUTH_TOKEN_CLIENT:
        required: true

jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      - name: create deployment
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `${{github.sha}}`,
              required_contexts: []
            })
