name: Reusable workflow example

on:
  deployment_status:

jobs:
  deployment-status:
    runs-on: ubuntu-latest

    # Continue only if some definitive status has been reported.
    if: github.event.deployment_status.state == 'success' && github.event.deployment.environment == 'carmen-staging'

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - run: |
          echo ${{ github.repository }}
          echo ${{ github.event.deployment.environment }}
          echo ${{ github.job  }}
      # Forward deployment's status to the deployed commit.
