name: Rollback Service (AWS)
on:
  workflow_dispatch:
    inputs:
      rollback_to_tag:
        description: "Release tag to rollback to"
        type: string

jobs:
  get-target-sha:
    runs-on: ubuntu-latest
    steps:
      - name: Rollback to the specific tag
        if: ${{ inputs.rollback_to_tag }}
        uses: actions/github-script@v6
        with:
          script: |
            const targetRelease = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: ${{ inputs.rollback_to_tag }}
            })
            console.log(targetRelease)
      - name: Rollback to second latest tag
        if: ${{ !inputs.rollback_to_tag }}
        uses: actions/github-script@v6
        with:
          script: |
            const releases = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,          
            })
            const secondLatestTag = releases.data[1].tag_name
            console.log(secondLatestTag)
            const targetRelease = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: secondLatestTag
            })
            console.log(targetRelease)

  get-last-tag:
    runs-on: ubuntu-latest
    if: ${{ !inputs.rollback_to_tag }}
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const latestRelease = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,          
            })
            console.log(latestRelease)

            const releases = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,          
            })
            console.log(releases)
