name: Reusable workflow example

on:
  deployment:
  deployment_status:
  push:

jobs:
  start-release:
    runs-on: ubuntu-latest
    # if: github.event.deployment.environment == 'carmen-staging'
    steps:
      - name: "test"
        run: |
          echo
      - name: Send GitHub trigger payload to Slack Workflow Builder
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          channel-id: "C02J77LD0NT" # ID of Slack Channel you want to post to
          payload: |
            {
              "attachments": [
                {
                  "blocks": [
                    {
                      "text": {
                        "text": "Starting a new release: :inprogress:",
                        "type": "plain_text",
                        "emoji": true
                      },
                      "type": "section"
                    }
                  ],
                  "color": "#FFC300"
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  release-notes:
    runs-on: ubuntu-latest

    # Continue only if some definitive status has been reported.
    # if: github.event.deployment_status.state == 'success' && github.event.deployment.environment == 'carmen-staging'
    needs: start-release
    steps:
      - name: send slack
        uses: slackapi/slack-github-action@v1.17.0
        with:
          channel-id: "C02J77LD0NT"
          payload: |
            {
              "attachments": [
                {
                  "blocks": [
                    {
                      "text": {
                        "text": "Release is completed on production. :done:",
                        "type": "plain_text",
                        "emoji": true
                      },
                      "type": "section"
                    }
                  ],
                  "color": "#00FF00"
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
