name: Rollback Service (AWS)
on:
  workflow_dispatch:
    inputs:
      rollback_to_tag:
        description: "Release tag to rollback to"
        type: string

jobs:
  get-target-sha:
    runs-on: ubuntu-latest
    steps:
      - name: Rollback to the specific tag
        if: ${{ inputs.rollback_to_tag }}
        uses: actions/github-script@v6
        with:
          script: |
            const targetRelease = await github.rest.git.getRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'tags/prod-2022-03-04-2'
            })
            console.log(targetRelease)
      - name: Rollback to second latest tag
        if: ${{ !inputs.rollback_to_tag }}
        uses: actions/github-script@v6
        with:
          script: |
            const releases = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,          
            })
            const secondLatestTag = releases.data[1].tag_name
            console.log(secondLatestTag)
            const targetRelease = await github.rest.git.getRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `tags/${secondLatestTag}`
            })
            console.log(targetRelease)
