name: Reusable workflow example

on:
  deployment_status:
  push:

jobs:
  start-release:
    runs-on: ubuntu-latest
    # if: github.event.deployment_status.action == 'created' && github.event.deployment.environment == 'carmen-staging'
    steps:
      - name: Send GitHub trigger payload to Slack Workflow Builder
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          channel-id: "test-updates-user-end-trial" # ID of Slack Channel you want to post to
          payload: |
            {
              "blocks": [
                { "type": "divider" },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Pick an item from the dropdown list"
                  },
                  "accessory": {
                    "type": "static_select",
                    "placeholder": {
                      "type": "plain_text",
                      "text": "select item",
                    },
                    "options": [
                      {
                        "text": {
                          "type": "plain_text"
                          "text": "text"
                        }
                      }
                    ]
                  }               
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "button"
                      },
                      "url": "https://media.makeameme.org/created/a-slack-this.jpg"
                    }
                  ]
                }
              ],
              "channel-id": "test-updates-user-end-trial"
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  # release-notes:
  #   runs-on: ubuntu-latest

  #   # Continue only if some definitive status has been reported.
  #   if: github.event.deployment_status.state == 'success' && github.event.deployment.environment == 'carmen-staging'

  #   steps:
  #     - name: send slack
  #       uses: slackapi/slack-github-action@v1.17.0
  #       with:
  #         channel-id: "test-updates-user-end-trial"
  #         slack-message: "done"
  #       env:
  #         SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  # Forward deployment's status to the deployed commit.
