name: Rollback Service (AWS)
on:
  workflow_dispatch:
    inputs:
      rollback_to_tag:
        description: "Release tag to rollback to"
        type: string

jobs:
  print-tag:
    runs-on: ubuntu-latest
    if: ${{ inputs.rollback_to_tag }}
    steps:
      - name: Print the input tag to STDOUT
        run: echo  The tags are ${{ inputs.rollback_to_tag }}
  get-last-tag:
    runs-on: ubuntu-latest
    if: ${{ !inputs.rollback_to_tag }}
    steps:
      - name: Print the input tag to STDOUT
      - uses: actions/github-script@v6
        with:
          script: |
            const latestRelease = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,          
            })
            console.log(latestRelease)
