name: Reusable workflow example

on:
  deployment_status:
  push:

jobs:
  start-release:
    runs-on: ubuntu-latest
    # if: github.event.deployment_status.action == 'created' && github.event.deployment.environment == 'carmen-staging'
    steps:
      - name: send slack
        uses: slackapi/slack-github-action@v1.17.0
        with:
          channel-id: "test-updates-user-end-trial"
          payload-file-path: "./release-manager.json"

        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  # release-notes:
  #   runs-on: ubuntu-latest

  #   # Continue only if some definitive status has been reported.
  #   if: github.event.deployment_status.state == 'success' && github.event.deployment.environment == 'carmen-staging'

  #   steps:
  #     - name: send slack
  #       uses: slackapi/slack-github-action@v1.17.0
  #       with:
  #         channel-id: "test-updates-user-end-trial"
  #         slack-message: "done"
  #       env:
  #         SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  # Forward deployment's status to the deployed commit.
