name: Reusable workflow example

on:
  workflow_call:
    secrets:
      SENTRY_AUTH_TOKEN_CLIENT:
        required: true

  push:

jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "something"
        run: |
          echo ${{secrets.SENTRY_AUTH_TOKEN_CLIENT}}
