name: Reusable workflow example

on:
  deployment_status:

jobs:
  deployment-status:
    runs-on: ubuntu-latest

    # Continue only if some definitive status has been reported.
    if: github.event.deployment_status.state != 'pending'

    steps:
      - name: Wait for 5 minutes
        run: |
          sleep 30
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - run: |
          echo ${{ github.repository }}
          echo ${{ github.event }}
          echo ${{ github.job  }}
      # Forward deployment's status to the deployed commit.
      - uses: octokit/request-action@v2.0.23
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          route: POST /repos/:repository/statuses/${{ github.event.deployment.sha }}
          repository: ${{ github.repository }}
          state: ${{ github.event.deployment_status.state }}
          target_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          description: >
            ${{ format('Heroku deployment is {0}', github.event.deployment_status.state) }}
          context: deployment-status
