name: Reusable workflow example

on:
  workflow_call:
    secrets:
      SENTRY_AUTH_TOKEN_CLIENT:
        required: true
      AWS_ACCESS_KEY_ID_FOR_AWS_DEV_ACCOUNT:
        required: true

  pull_request:
    types: [labeled]

jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "something"
        run: |
          echo ${{secrets.SENTRY_AUTH_TOKEN_CLIENT}}
