name: Reusable workflow example

on:
  workflow_call:
  pull_request:
    types: [labeled]

jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      - name: "something"
        run: |
          echo "run worflow a"
